### ISSUE TITLE
Clean the top-level source of obosolete files and dirs

### ISSUE THREAD

**Issue by winterz** [libical/libical#761]
Review these files/dirs in the top-level.  can we remove/move them or turn them into github issues
- [x] TEST : contains 1 useful line that says "Use iCAL keywords as first words of unquoted strings".  make this a github issue? (fixed in #773 )
- [x] TODO: anything not done should be converted into a github issue
- [x] THANKS - keep. modernize.  might be a good chapter for the manual (fixed in #776)
- [x] debian/ - hasn't been touched in a long, long time.  I can't imagine we still need it (fixed in #772 )
- [x] AUTHORS - kinda useless as is.  I guess we can keep.  we have the THANKS file too.  Maybe merge AUTHORS and THANKS. (fixed in #775)
- [x] COPYING. almost identical to LICENSE.txt.  I don't think we need both. maybe merge COPYING into LICENSE.txt and then remove COPYING. probable hold-over from the GNU project style (fixed n #774 )
